version: '3.3'
services:
  postgres:
    image: postgres:10.4
    networks:
      - jenkins_default
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    deploy:
      placement:
        constraints: [node.labels.ostype==linux]
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins_default
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: P@ssw0rd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    deploy:
      placement:
        constraints: [node.labels.ostype==linux]
    depends_on: 
      - postgres
secrets:
  postgres-passwd:
    external: true
networks:
  jenkins_default:
    external: true