version: '3.3'
services:
  owaspweb:
    image: 137.116.133.205:8443/admin/owaspweb:${commit_id}
  sigsci-agent:
    image: 137.116.133.205:8443/admin/sigsci-agent:latest
    environment:
            SIGSCI_ACCESSKEYID: 'be8b5287-142c-416d-9773-ed0f2bc87bca'
            SIGSCI_SECRETACCESSKEY: 'XHxw00Tpr-bpjomfMtXqB-N7RWhq9-HWEKmArtx6V2Y'
            SIGSCI_REVERSE_PROXY: 'true'
            SIGSCI_REVERSE_PROXY_LISTENER: '0.0.0.0:8081'
            SIGSCI_REVERSE_PROXY_UPSTREAM: 'owaspweb:3000'
        ports:
            -  11081:8081 
         